import React from "react";
import "../globals.css";
import FormUpdate from "@/components/create-campaign/FormUpdate";
import { Metadata } from "next";
import { Sora } from "next/font/google";
const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={` ${sora.className} bg-[#F4F9FC] max-w-[144rem] mx-auto  `}
      >
        <div className="grid grid-cols-[20rem_1fr] h-screen">
          <FormUpdate />

          <div className="bg-white  rounded-tl-[150px] ">
            {/* {children} */}
          </div>
        </div>
      </body>
    </html>
  );
}
