import React from "react";
import "../globals.css";
import { Metadata } from "next";
import { Sora } from "next/font/google";
import { Toaster } from "sonner";
const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={` ${sora.className} bg-[#F4F9FC]   `}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
