import { TokenObjectType } from "@/services/contracts/tokensConfig";
import { ChainDocument } from "./chain.types";
import { CommentDocument } from "./comment.types";
import { UserDocument } from "./user.types";
import { TokenDocument } from "./token.types";

export type CampaignDocument = {
  title: string;
  description: string;
  image: File;
  coverImage: File;
  otherImages: File[];
  category: string;
  targetAmount: number;
  startDate: string;
  endDate: string;
  chain: string;
  creator: string;
  tokenAddresses: string[];
};
export type ReturnCampaignDocument = {
  title: string;
  description: string;
  image: string;
  coverImage: string;
  otherImages: string[];
  category: string;
  targetAmount: number;
  currentAmount: number;
  owner: UserDocument;
  startDate: string;
  endDate: string;
  chain: ChainDocument;
  ipfsId: string;
  creator: string;
  comments: CommentDocument[];
  likes: number;
  seen: number;
  cmid: string;
  published: boolean;
  tokens: TokenDocument[];
  campaignAddress?: string;
};
