export const CategorisItem = [
  {
    id: 1,
    image: "/layout/Frame.png",
    timeleft: "3days left",
    title: "Help Fund Life-Saving Surgeries",
    creatorimage: "/layout/Ellipse.png",
    creatorname: "Tade Lawal",
    story:
      "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
    fundrasied: "$7000",
    fundtarget: "$1600",
    category: "creatives",
  },
  // {
  //   id: 2,
  //   image: "/layout/Frame.png",
  //   timeleft: "3days left",
  //   title: "Help Fund Life-Saving Surgeries",
  //   creatorimage: "/layout/Ellipse.png",
  //   creatorname: "Tade Lawal",
  //   story:
  //     "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
  //   fundrasied: "$7000",
  //   fundtarget: "$1600",
  //   category: "personal",
  // },
  {
    id: 3,
    image: "/layout/Frame.png",
    timeleft: "3days left",
    title: "Help Fund Life-Saving Surgeries",
    creatorimage: "/layout/Ellipse.png",
    creatorname: "Tade Lawal",
    story:
      "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
    fundrasied: "$7000",
    fundtarget: "$1600",
    category: "organisation",
  },
  {
    id: 4,
    image: "/layout/Frame.png",
    timeleft: "3days left",
    title: "Help Fund Life-Saving Surgeries",
    creatorimage: "/layout/Ellipse.png",
    creatorname: "Tade Lawal",
    story:
      "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
    fundrasied: "$7000",
    fundtarget: "$1600",
    category: "community rescue",
  },
  {
    id: 5,
    image: "/layout/Frame.png",
    timeleft: "3days left",
    title: "Help Fund Life-Saving Surgeries",
    creatorimage: "/layout/Ellipse.png",
    creatorname: "Tade Lawal",
    story:
      "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
    fundrasied: "$7000",
    fundtarget: "$1600",
    category: "crisis relief",
  },
  {
    id: 6,
    image: "/layout/Frame.png",
    timeleft: "3days left",
    title: "Help Fund Life-Saving Surgeries",
    creatorimage: "/layout/Ellipse.png",
    creatorname: "Tade Lawal",
    story:
      "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
    fundrasied: "$7000",
    fundtarget: "$1600",
    category: "education",
  },
  {
    id: 7,
    image: "/layout/Frame.png",
    timeleft: "3days left",
    title: "Help Fund Life-Saving Surgeries",
    creatorimage: "/layout/Ellipse.png",
    creatorname: "Tade Lawal",
    story:
      "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
    fundrasied: "$7000",
    fundtarget: "$1600",
    category: "Travel",
  },
  {
    id: 8,
    image: "/layout/Frame.png",
    timeleft: "3days left",
    title: "Help Fund Life-Saving Surgeries",
    creatorimage: "/layout/Ellipse.png",
    creatorname: "Tade Lawal",
    story:
      "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
    fundrasied: "$7000",
    fundtarget: "$1600",
    category: "health",
  },
  {
    id: 9,
    image: "/layout/Frame.png",
    timeleft: "3days left",
    title: "Help Fund Life-Saving Surgeries",
    creatorimage: "/layout/Ellipse.png",
    creatorname: "Tade Lawal",
    story:
      "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
    fundrasied: "$7000",
    fundtarget: "$1600",
    category: "verified",
  },

  {
    id: 10,
    image: "/layout/Frame.png",
    timeleft: "3days left",
    title: "Help Fund Life-Saving Surgeries",
    creatorimage: "/layout/Ellipse.png",
    creatorname: "Tade Lawal",
    story:
      "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
    fundrasied: "$7000",
    fundtarget: "$1600",
    category: "for you",
  },
  {
    id: 11,
    image: "/layout/Frame.png",
    timeleft: "3days left",
    title: "Help Fund Life-Saving Surgeries",
    creatorimage: "/layout/Ellipse.png",
    creatorname: "Tade Lawal",
    story:
      "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
    fundrasied: "$7000",
    fundtarget: "$1600",
    category: "health",
  },
  {
    id: 12,
    image: "/layout/Frame.png",
    timeleft: "3days left",
    title: "Help Fund Life-Saving Surgeries",
    creatorimage: "/layout/Ellipse.png",
    creatorname: "Tade Lawal",
    story:
      "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
    fundrasied: "$7000",
    fundtarget: "$1600",
    category: "edication",
  },
  {
    id: 13,
    image: "/layout/Frame.png",
    timeleft: "3days left",
    title: "Help Fund Life-Saving Surgeries",
    creatorimage: "/layout/Ellipse.png",
    creatorname: "Tade Lawal",
    story:
      "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
    fundrasied: "$7000",
    fundtarget: "$1600",
    category: "Trending",
  },
  //   {
  //     id: 14,
  //     image: "/layout/Frame.png",
  //     timeleft: "3days left",
  //     title: "Help Fund Life-Saving Surgeries",
  //     creatorimage: "/layout/Ellipse.png",
  //     creatorname: "Tade Lawal",
  //     story:
  //       "Support medical supplies and treatments for underserved communities.Support medical supplies and treatments for underserved communities.",
  //     fundrasied: "$7000",
  //     fundtarget: "$1600",
  //     category: "for you",
  //   },
];
