export const List = [
  {
    id: 1,
    image: "/layout/cam.png",
    title: "Rural Development Projects",
    name: "Tade Lawal",
    amount: "2400",
    goal: "34",
    donoeNumber: 2400,
    status: "in-progress",
  },
  {
    id: 2,
    image: "/layout/cam.png",
    title: "Rural Development Projects",
    name: "Tade Lawal",
    amount: "2400",
    goal: "34",
    donoeNumber: 2400,
    status: "completed",
  },
  {
    id: 3,
    image: "/layout/cam.png",
    title: "Rural Development Projects",
    name: "Tade Lawal",
    amount: "2400",
    goal: "34",
    donoeNumber: 2400,
    status: "completed",
  },
  {
    id: 4,
    image: "/layout/cam.png",
    title: "Rural Development Projects",
    name: "Tade Lawal",
    amount: "2400",
    goal: "34",
    donoeNumber: 2400,
    status: "in-progress",
  },
];
